version: '3'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 11111
  app:
    image: kinecosystem/app_registration:6c783d9
    ports:
      - 3000:3000
#    network_mode: host
    environment:
      PYTHON_PASSWORD: 1234
      POSTGRES_PASSWORD: 11111
      DB_NAME: 'application_data'
      DB_HOST: 'db'
      API_KEY: 'One kin to rule them all'
