version: '3'

services:
  app:
    image: kinecosystem/app_id_registration:18a6950
    build:
       context: .
    ports:
      - 3000:3000
    environment:
      API_KEY: 'One Ring To Rule Them All'
      PYTHON_PASSWORD: 'Q3ZHni@ecIPa'
      DB_PASSWORD: '11111'
      DB_NAME: 'applications'
      DB_HOST: 'db'
      DB_ROLE: 'postgres'
