version: '3'

services:
  app:
    image: kinecosystem/app_id_registration:2103122
    network_mode: host # To connect to datadog agent
    build:
       context: .
    ports:
      - 3000:3000
    environment:
      API_KEY: 'One Ring To Rule Them All'
      PYTHON_PASSWORD: '1234'
      DB_PASSWORD: '11111'
      DB_NAME: 'applications_db'
      DB_HOST: 'db'
      DB_ROLE: 'postgres'
