version: '3'

 # docker-compose -f docker-compose.yml -f docker-compose.local.yml up
services:
  db:
    image: postgres:11-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 11111

  app:
    image: kinecosystem/app_id_registration:20190701
    ports:
      - 3000:3000
    environment:
      API_KEY: 'One Ring To Rule Them All'
      PYTHON_PASSWORD: '1234'
      DB_PASSWORD: '11111'
      DB_NAME: 'applications_db'
      DB_HOST: 'db'
      DB_ROLE: 'postgres'
